### PR TITLE
dryrun mode functions for appsody operator install/uninstall appsody deploy

### LINKED ISSUE #219: appsody deploy --dryrun fails if the deployment yaml has not been created yet
**Describe the bug**
`appsody deploy --dryrun` will give an error if the deployment yaml (ex: app-deploy.yaml) has not been created 

**To Reproduce**
0. run docker desktop and its k8s
1. `mkdir nodejs`
2. `cd nodejs`
3. `appsody init nodejs`
4. `appsody deploy --dryrun`

**Expected behavior**
expecting no error messages

**Actual behaviour**
```
supra:nodejs2 tnixa$ appsody deploy --dryrun
Attempting to get resource from Kubernetes ...
Dry run - skipping execution of: kubectl [get service/appsody-operator --namespace default]
Dry Run - Skip writing config file /Users/tnixa/.appsody/.appsody.yaml
Dry run - skipping execution of: docker [pull appsody/nodejs:0.2]
Dry Run - Skipping command: docker[create --name nodejs2-extract appsody/nodejs:0.2]
Dry Run - Skipping command: docker[cp nodejs2-extract:/config/app-deploy.yaml ./app-deploy.yaml]
Dry Run - Skipping command: docker[rm nodejs2-extract -f]
[Error] Config file does not exist app-deploy.yaml.
```

**Environment Details (please complete the following information):**
 - OS: mac

**If applicable please specify:**
 - CLI version: 0.3.0 plus fixes
 - Stack you are using: nodejs

### PR DESCRIPTION
**Pull request by kewegner**
Fixes #219
Made the appropriate changes so that dry run mode functions with:
appsody deploy --dryrun
appsody operator install --dryrun
appsody operator uninstall --dryrun

### CODE REVIEW

File: cmd/operator_uninstall.go [hunk 1]
```diff
@@ -104,24 +106,30 @@ func removeOperatorRBAC(operatorNamespace string) error {
...
-	if err != nil {
-		return err
+	if !dryrun {
+		watchNamespace, err = getOperatorWatchspace(operatorNamespace)
+		Debug.logf("Operator is watching the '%s' namespace", watchNamespace)
+		if err != nil {
+			return err
+		}
+	} else {
+		Info.log("Dry run - skipping execution of: getOperaotWatchspace(" + operatorNamespace + ")")
```
Comment (chilanti) [inline cmd/operator_uninstall.go]: Typo on the error message
