### PR TITLE
Fix: Windows Bind Mount Path

### LINKED ISSUE #912: Paths in bind mounts on Win10 at certain Docker Desktop versions break many appsody commands
**Describe the bug**

At my level of Docker Desktop, the appsody commands using bind mounts:
 **init,  extract/build, run/debug/test** etc. (all of them?)
fail with errors like:  `[Container] docker: Error response from daemon: file does not exist.`

E.g.

> $ appsody test
> Running test environment
> Using local cache for image dev.local/appsody/java-openliberty:0.2
> Running command: docker run --rm -p 9080:9080 -p 9443:9443 -p 7777:7777 --name ol2e-dev -v C:/Users/ScottKurz/.m2/repository:/mvn/repository -v C:/ydosppa/apps/ol2e/.:/project/user-app -v appsody-controller-0.3.4:/.appsody -t --entrypoint /.appsody/appsody-controller dev.local/appsody/java-openliberty:0.2 --mode=test
> [Container] docker: Error response from daemon: file does not exist.
> [Container] See 'docker run --help'.
> [Error] Error in 'appsody test': exit status 125
> 
> 

**To Reproduce**

Simply do
* `appsody init java-openliberty`     (you see the problem as a warning but you could ignore and continue)
* `appsody run`

**Environment Details (please complete the following information):**
 - OS: Win 10 Build 1903
- Docker Desktop v2.2.0.3

**If applicable please specify:**
 - appsody CLI v0.5.8
 - Stack you are using: java-openliberty

**Additional context**
Naturally I'd like to know how was this working before for me on Win10?

I believe I was on  Docker Desktop Edge v2.1.7.0 when it worked at the same level of appsody

**Workaround**

Each individual Docker command can be "fixed" manually by adjusting the bind mount path to remove the "dot-slash" (./), e.g.:

Change:
`docker run --rm -p 9080:9080 -p 9443:9443 -p 7777:7777 --name ol2e-dev -v C:/Users/ScottKurz/.m2/repository:/mvn/repository -v C:/ydosppa/apps/ol2e/.:/project/user-app ....`
to:
`docker run --rm -p 9080:9080 -p 9443:9443 -p 7777:7777 --name ol2e-dev -v C:/Users/ScottKurz/.m2/repository:/mvn/repository -v C:/ydosppa/apps/ol2e:/project/user-app ....`

Of course, this doesn't help for `appsody build`

### PR DESCRIPTION
**Pull request by scottkurz**
Signed-off-by: Scott Kurz <skurz@us.ibm.com>

Fixes #912 .

I'm not easily able to test this at levels other than the ones I mentioned when opening issue #912, but I did have a colleague try my patch and he is able to do `appsody run` on Win 10 both with and without my fix.

In other words, I don't think I regressed anyone based on that one test, but more review would be appreciated.

### CODE REVIEW

File: cmd/utils.go [hunk 1]
```diff
@@ -314,6 +314,9 @@ func getVolumeArgs(config *RootCommandConfig) ([]string, error) {
 			mappedMount = strings.Replace(mount, "~", homeDir, 1)
 			overridden = homeDirOverridden
 		} else {
+			if strings.HasPrefix(mount, ".:") {
```
Comment (EnriqueL8) [inline cmd/utils.go]: Maybe another options would be to use `$(pwd)`?

Comment (scottkurz) [reply cmd/utils.go]: @EnriqueL8 not following since that's a shell expansion and I'm not too familiar with Go.   Do you mean something like: `https://golang.org/pkg/os/#Getwd` ?
